### PR TITLE
Error forwarding

### LINKED ISSUE #133: Implement error forwarding
When a mutable message (constructor or otherwise) is dry-run as an RPC the UI should properly decode the returned value and classify it as error or success.

Please note that there are three different layers of failure:

1. Something failed on the json rpc level. Usually some programming error or totally invalid input. Bug in js or sce probably.
2. The dispatchable failed: This means that the contract had no chance to return any decodeble data but rather failed without doing so.
3. The contract execution finished but the `flags` contain the revert bit (the least significant bit). In this case the output buffer should be decoded and displayed as an error (just as in case 2).

This issue is about the 3. error layer because I assume the first two are already implemented.

Please note that the output buffer should always be decoded and presented to the user. The tricky part is to check for the revert flag to properly indicate that it is an error.

@cmichi 

https://github.com/polkadot-js/apps/issues/6465

### PR DESCRIPTION
**Pull request by achimcc**
Closes #133 

Implements the following:

- reads the `flags` from RPC dry-run result, throws an error if revert bit is set
- displays RPC dry-run results in UI
- ~~disables Call button if RPC dry-run was not successfull~~

As discussed with @statictype , we don't disable the Call button when the dry-run was not successfull.

### CODE REVIEW

**Comment by statictype** [comment]
we can merge this, it's definitely a good step forward. but i think the issue was also about displaying the actual error that happened and caused the contract to revert. can you confirm @athei ?
anyway, we should first reach a final design decision about how to display dry run results on the Interact page (discussed [here](https://github.com/paritytech/contracts-ui/issues/74)) before continuing with this issue

one comment though before we can merge:
i'm seeing "RPC dry-run successfull" below the read button for getters like `total_supply` and  `balance_of`, it should only be displayed below dispatchables
we currently display the `gasComponent` there but do we even need to pay gas for calling `total_supply`?

**Comment by athei** [comment]
Okay I played around with it a bit. It does not resolve the issue:
* It does not show the error returned (the actual error returned by the RPC). It merely says that there was a reversion.
* I think all the information should be in the "Call Result"  box (maybe flagging it as a "dry-run)
* Gas estimation is broken on revert: It falls back to a default value
* It only detects a reversion but no other error -> any error happening in the dry run should be reported
* The output buffer containing the error responsible for the reversion is not decoded.

**Comment by achimcc** [comment]
It does also report errors on the RPC level now, which were also not reported before, but only logged to the console.

I will change it so that we display all dry-run results in the "Call Result" box.

One question remains: should we still execute the dry-run automatically when the page loads or should we add a "dry-run" button to the page?

**Comment by athei** [comment]
If you ask me: There should be no button. Just run it on page load and on input change.

**Comment by kwingram25** [comment]
I remember we discussed possibilities a bit earlier this week. Maybe what we could do is have two panels to the side - one for past execution results as we currently, and one to show the result for the current call in real time, either the dryrun for a TX or just the read result for an RPC. Then a button in that panel that would either sign and send the TX, or save the current RPC result to the execution log, depending on which of the two it is?

**Comment by athei** [comment]
> Maybe what we could do is have two panels to the side - one for past execution results as we currently, and one to show the result for the current call in real time, either the dryrun for a TX or just the read result for an RPC.

This sounds great.

> Then a button in that panel that would either sign and send the TX, or save the current RPC result to the execution log, depending on which of the two it is?

You mean depending on whether the message is read only or not? I don't think there is any reason to save anything to the execution log for read only messages (getters). I like the approach of polkadot.js for this. They don't have any interactions with getters there but just show the current value at all times. Have you checked that out?

**Comment by kwingram25** [comment]
I believe it's only for getters with no parameters isn't it?

The idea for saving current results to the log is to let you track how the value changes over time. So you get a value once, send a transaction, and then can compare it to what it used to be.

**Comment by athei** [comment]
> I believe it's only for getters with no parameters isn't it?

Not sure. Maybe. I think we should keep the value displayed inline even for getters with arguments. We can update the inline displayed value on input change.

> The idea for saving current results to the log is to let you track how the value changes over time. So you get a value once, save it, send a transaction, and then can compare it to what it used to be.

I can't really tell if that is a useful feature to manually log them there. If you see any of those logged values in the history you will never now if the value had changed in between. I would rather use something where I toggle something like  "watch value" and then we log every change there.

> Could also add the ability to "pin" getters - so you could see the balanceOf for a particular account as it changed, for example.

Yeah this could be an extension to the inline display of getters. Add multiple rows there for different values.

**Comment by statictype** [comment]
done for instantiate in https://github.com/paritytech/contracts-ui/pull/209
will be done for call in https://github.com/paritytech/contracts-ui/issues/297

**Pull request closed without merging**
