### PR TITLE
fix: pretty print dry-run results

### PR DESCRIPTION
**Pull request by statictype**
related to https://github.com/paritytech/contracts-ui/issues/421

### CODE REVIEW

**Comment by peetzweg** [comment]
I tried to review this yesterday a bit. Code wise it looks good to me. However, I wasn't able yet to find a contract which has a struct returned like `cmichi` described. Will reach out to grab the contract or could just probably adapt the flipper one. 🤔

**Comment by statictype** [comment]
try [this one](https://github.com/paritytech/ink/tree/master/integration-tests/mother). it returns a struct too.

**Comment by peetzweg** [comment]
Not to sure if this is what @cmichi asked for in the ticket. Proper strings now lose the quotation marks `"`. Sure `Number`s are now without quotes but the dry-run results is not not even valid JSON.

Frame 1(1)


When reading the ticket I was more imagining something like this. Where the `toString()` representation contains the actual rust type. Not sure how this is commonly done but it could look like this.

```json
{
	"name": "String('This is a String')",
	"subject": "Hash(0x0000000000000000000000000000000000000000000000000000000000000000)",
	"bids": "Vec[
		  Vec[
			Option[
				AccountId('5GrwvaEF5zXb26Fz9rcQpDWS57CtERHpNehXCPcNoHGKutQY'),
				uint128('100')
			]
		]
	],
	"terms": [
		"Number('0')",
                "Number('1')",
                "Number('2')"
	],
	"status": "Status('OpeningPeriod')",
	"finalized": "Boolean(true)",
	"vector": "Vec<u8>('A Vec<u8> :shrug:')"
}
```

**Comment by statictype** [comment]
No that's not what we want. We need to show the dry-run outcome as it comes back from chain. 
We don't have the type information of the individual struct fields there. It could be possible but at but it is an insane computation given that the result can be anything. 
What i wanted to achieve with this PR is to remove all the quotes that come with `JSON.stringify`. 
This means also removing quotes around strings, as a tradeoff
We don't need this to be valid JSON, it is just printed to the screen, not used anywhere.

**Review by peetzweg — DISMISSED** [review]
@statictype 
Just got a bit more into the polkadotjs registry stuff to code and decode data. Surely it's tricky to do adapt the displayed output in such a generic case.

There seems to be "settings" to adapt the transformation of primitives.
Docs: 
>toHuman() - returns Human-parsable JSON structure with values formatted as per the **settings**

But as you mentioned the docs are not always correct or up to date.

`toHuman()` seems to have this weird `isExtended` flag which might be related to this. 

```ts
/**
 * @description Converts the Object to to a human-friendly JSON, with additional fields, expansion and formatting of information
 */
toHuman(isExtended?: boolean): AnyJson;
```

----

Anyways it's not as simple for sure to do the formatting. I personally think this toHuman() json output is valid and fine for me and I don't understand the actual benefit of removing the `"'` quotes from it. 🤷 

As I'm not not a power user of the interface yet you know best what is useful. 👍

**Comment by statictype** [comment]
`toHuman() ` decodes anything, it is available on any `Codec` interface. it has no type information whatsoever though. 
in the case of structs it returns an object which needs to be stringified in order to be displayed to the screen. the actual result we want to display often comes nested so just calling `toHuman` on the result isn't enough.
I added a different approach which strips strings only from the object keys

**Review by peetzweg — APPROVED** [review]

**Pull request merged**
