### PR TITLE
feat: Ethereum accounts

### PR DESCRIPTION
**Pull request by JoshOrndorff**
This PR demonstrates how to enable Etheruem-style accounts in the contracts-ui.

Eventually this could solve #492 . But I would request some help from a project maintainer in finishing this up.

This is only a demonstration because this PR, as it is currently written, switches the UI to use ethereum accounts always. Rather we need to provide a setting for the user. Ideally we could add a param to the url so I could link to something like `contracts-ui.substrate.io/?account-type=ethereum` or similar.

### CODE REVIEW

**Comment by JoshOrndorff** [comment]
Wonderful! Yes! This makes the contracts ui detect whether it is dealing with an ethereum chain just like Polkadot JS Apps does.

I'm testing it locally and all is well. I would love it if we could get this change into the hosted contracts UI in time for the PBA on July 10th

**Comment by statictype** [comment]
@JoshOrndorff what else is needed? can we merge as is?
do we need to support the full list of [ethereum chains](https://github.com/paritytech/contracts-ui/blob/ca60fadafea584a545fd496c6b043d81fc6fb26f/src/constants/index.ts#L122)?

**Comment by JoshOrndorff** [comment]
For me, there is nothing else needed. This solves the exact problem I had and I'm very grateful for your help :pray: .

> do we need to support the full list of [ethereum chains](https://github.com/paritytech/contracts-ui/blob/ca60fadafea584a545fd496c6b043d81fc6fb26f/src/constants/index.ts#L122)?

Some of these chains don't have pallet contracts installed (for example moonbeam does not, and probably many others), so you may prefer to remove those chains. OTOH, it is only a few bytes of source code, and it may make more sense to just keep the list updated with Polkadot JS upstream rather than have your own process. IMO I would just keep the whole list, but if you want to make it smaller, I think that is fine.

For me the only spec name you _must_ keep is `frontier-template` because that's the one I'm starting from.

**Review by statictype — APPROVED** [review]

**Comment by JoshOrndorff** [comment]
Hooray! Thank you for your help @statictype . Very much appreciated. The students at PBA will have a fun time working on contracts with this UI feature.

**Pull request merged**
