### PR TITLE
feat: use `<InputBytes/>` for `[u8, n]` type

### LINKED ISSUE #416: Better Input for Fixed-Length Arrays (`[T, N]`)
**Is your feature request related to a problem? Please describe.**
When inputting a fixed length array like a `[u8;20]` (an EVM Address), it is frustrating and not practical enough to input each `u8` separately.

**Describe the solution you'd like**
For fixed length bytes array, input should also provide option to input hex-encoded strings, like polkadot-js provides.

**Additional context**
image

### PR DESCRIPTION
**Pull request by peetzweg**
makes use of `<InputBytes/>` for `VecFixed` with Sub u8, which is usually easier to input encoded has hex. Closes #416.

Using the plain `Input` component to recreate some behavior of the InputHex one. However doing the checking hex step in the `validation` function. Therefore allowing not hex characters, but allows for empty value and less hassle of pasting a copied hex string to this input field.

Tested with `String`, `Hash` and `Vec<u8>` types if there is some overlap regarding input rendering. These inputs are not touched by this PR.

https://github.com/paritytech/contracts-ui/assets/839848/4e715f5e-0411-411c-90d6-fd4cbfbfca24

Contract `input-types`:

https://filebin.net/41e8q8cyl9yvf1g9

### CODE REVIEW

**Comment by statictype** [comment]
the input doesn't allow users to type unwanted characters, if we allow '0x' in there at the beginning, validation gets trickier.
if you want to write this regex be my guest :)

**Review by statictype — COMMENTED** [review]
seems like you modified this component to mimic the behaviour of `InputHash`. just wondering why not use that directly?

**Comment by peetzweg** [comment]
> seems like you modified this component to mimic the behaviour of `InputHash`. just wondering why not use that directly?

The `InputHash` turns the resulting value into a `H256`, but we this input should turn it into a `Uint8Array`. So this is actually what the previously unused `InputBytes` does. Just added a length prop to define how many bytes hex encoded to expect.

https://github.com/paritytech/contracts-ui/blob/b526ff13cad048f6954063b3e2f130d9b9283121/src/ui/components/form/InputHash.tsx#L33-L34

https://github.com/paritytech/contracts-ui/blob/b526ff13cad048f6954063b3e2f130d9b9283121/src/ui/components/form/InputBytes.tsx#L41

**Comment by statictype** [comment]
LGTM!

@Maar-io can you please test the deploy preview to make sure it's working for your use cases?
https://deploy-preview-496--contracts-ui.netlify.app/

**Review by statictype — APPROVED** [review]

**Comment by peetzweg** [comment]
Just pinging @Maar-io again. Can you confirm this is solving your issue #416 ?

https://github.com/paritytech/contracts-ui/pull/496#issuecomment-1629121611

**Comment by Maar-io** [comment]
I can confirm it works as expected. Great work team and thank you!!!

Screenshot 2023-07-17 at 13 07 01

**Pull request merged**
